BBBBBBB BBBBBBBBBBB
BBBB BBBBBB

BBBBB BBBBBBBBBBB
    XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXX
        XXXXXX
    XXXXXX
BBBBBBBB

BBBBB BBBBBBB
    XXXX XXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXX
            XXXX XXXXXXXXXX XXXXXXXXXXX XXXXXX
                XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXX XXXXXX
            XXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXX
                XXXX XXXXXXXXXX XXXX XXXXXX
                    XXXX XXXXXXXXXXXXX XXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX
                            XXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXX XXXXXXXBB BBBBBBBBBBBBBBB BB BBBBBBBBBBBXXXXBBBBXXXXXBBBBBXX
                                XXXXXXX XXXXXXXXXXXXX BB BBBBBBBBBBBBBBB BB BBBBBBBBBBBXXXXXXXXBBBBBXXXXX XXXXXXXXXXXXXX
                                XXXXXXX XXXXXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBB BB BBBBBBBBBBBBXXXXXXXXBBBBBXXXXXXX XXXX XX XXXXXXXXXXXXXX
                                XXXXXXX XXXXXXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBB BB BBBBBBBBBBBBBXXXXXXXXBBBBBXXXXXXX XXXXX XX XXXXXXXXXXXXX
                                XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBB BB BBBBBBBBBBXXXXXXXXBBBBBXXXXX XXXXXXXXXXXXXX
                                XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBB BB BBBBBBBBBBBXXXXXXXXBBBBBXXXXX XXXXXXXXXXXXXX
                            XXXXXXXXX
                        XXXXXX
                    XXXXXX
                    XXXX XXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXX
                        XX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXXXXXXXXX
                            BB BBBBBBBBBBB BB BBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBB BB BBBBBBBBBBB
                                XXXXX XXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBXXXXXXXXXX XXXXXXXX X XXXXXXX
                            BBBBB
                            FFFFFF XXXXXXXXBB BBBBBBBBBBB XXXXX XXX XXXXXXXXXXXXXXXXXXXBBBBB
                        XXXX
                    XXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXX
                    BBB BBBBBBB BB BBBBBBBB
                        XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXXX
                            XXXX XXXXXXXXXXX XXXXX XXXXXXXXXX
                                BB BBBBBBBBBBBBB
                                XX XXXXXXBBB BBBBBBBBBBBBBBBB BBBBBBBBBBXX
                                    XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXX
                                XXXX
                                BBBB
                                XX XXXXXXBBB BBBBBBBBBBBBBBBB BBBBBBBBBBXX
                                    XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX
                                XXXX
                                BBBBB
                                XXXX XXXXXXXXXXXXXXXX XXXXXX
                                    XX XXXXXXXXXXXXXXXXX
    				                XX XXXXXXXXXXXXXXXXXXXXXX
                                    XX XXXXXXXXXXXXXXXXXX
                                    BBB BBBBBB BB BBBBBBBBBBBBBBBBBBBB
                                        XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                                        
                                        XXXX
                                    BBBBBB
                                XXXXXX

                                XXXX XXXXXXXXXXXXXXXXXX XXXXXXXX XXXX XXXXXXXX XXXXXXXXXXX
                                    XXXX XXXXXXXXXXXX
                                        XXXX XXXXXXXXXXXX
                                            XX XXXXXXXXXXX XXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX

                                            BB BBBBBBBBBBBBBBBBBBBBBBBBB
                                                XXXXXX XXXXXXXXXXXXX
                                                    XX XXXXXXBBB BBBBBBBBBBBBBB BBBBBBBBBBXXXXXXXXXX X 
                                                    XX XXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBB BBBBBBBBBBXXXXXXXXXXXX
                                                XXXXXXXX
                                            BBBBB
                                        XXXXXX
                                    XXXXXX
                                XXXXXX
                            XXXXXX
                        XXXXXX
                        BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                            XXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXX
                                XXXX
                            XXXXXX
                        BBBBB                        
                    BBBBBB
                XXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXX XXXXXXXXXXXXXX
        XX XXXXXXXXXXXXXXX XXXXXX XXXXXXX
            XX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXX
        XXXX	
    XXXXXX
BBBBBBBB

BBBBB BBBBBBBBBB
    
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
		XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
			XXXXXXXXXXXXXXXXXXXX
		XX
	XXXXXXXXX
    
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
            XXX XXXXXXXX X XXXXXXXX
            XXX XXXXXXXXXX X XXX XXXXXXXXXXXXXXXXXXXXX

            XXX XXXXXXXXXXX X XXXXXXXXXXXXXXX
            XXXXXXXXXXXXXX XX XXXXXXXXX
                XXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXX
                XXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXX

                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX

                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            X XXXX X
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            X
        XX
    XXXXXXXXX
BBBBBBBB