BBBBBBB BBBBBBBBBBB
BBBB BBBBBB

BBBBB BBBBBBBBBBB
    XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXX
        XXXXXX
    XXXXXX
BBBBBBBB

BBBBB BBBBBBB
    XXXX XXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXX
            XXXX XXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXX
                    BB BBBBBBBBBBBBB
                        XX XXXXXXX XXXXXXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXX
                        XXXX
                        BBBB
                        XX XXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX
                        XXXX
                    BBBBB
                XXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXX XXXXXXXX XXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXX
                    XX XXXXXXXXXXXXXXXXX
                    XX XXXXXXXXXXX XXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                    BB BBBBBBBBBBBBBBBBBBBBBBBBB
                        XXXXXX XXXXXXXXXXXXX
                            XX XXXXXXBBB BBBBBBBBBBBBBB BBBBBBBBBBXXXXXXXXXX X 
                            XX XXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBB BBBBBBBBBBXXXXXXXXXXXX
                        XXXXXXXX
                    BBBBB
                    XX XXXXXXXXXXXXXXXXX
                XXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
BBBBBBBB

BBBBB BBBBBBBBBB

BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBB