# Generated by Django 3.1.1 on 2020-10-18 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlanWorkout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_id', models.CharField(max_length=254, null=True)),
                ('workout_id', models.TextField(null=True)),
                ('repetitions', models.IntegerField(null=True)),
            ],
        ),
    ]
