# Generated by Django 3.1.1 on 2020-10-19 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_auto_20201017_1107'),
        ('planworkouts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planworkout',
            name='workout_id',
        ),
        migrations.AlterField(
            model_name='planworkout',
            name='plan_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='plans.plan'),
        ),
    ]
