XXXXXXXXXXXXXXXX XXXXXX XFFFFFFFFFFFFFXXXXXXXXXXXXXX
XXXXXXXXXXXXX XFFFFFFFFFFFFFXXXXX
XXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX XFFFFFFFFFFFFFXXXXXXXXXXXXXX
BB BBBBBBBBBBBBBBBBBBB B B
    XX XXXXXXXXXXX XXXXXXXXXXXXX
        XXX XXXXX XXX XXXX XXXXXXXX XX XXXXXXXX XXXX XXXXXXXXXXXXXXXXXX XXXXX
    XXXX
BBBBB