XX XXXXXXBBB BBBBBBBBBBX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXX
    XXXXX XXXXXXXXXXXXX
        XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
    XXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
XXXX
XX XXXXXXBBB BBBBBBBBBBX XXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXX
        XX XXXXXXXXXX XXXXXXXXXXXXX
    XXXXXXX
XXXX