XXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBB BBBBBBBBBBBBXX
    BBBBBBBBBB
    XXXX XXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXX XXXXXXXXXXXXXXXXXXXX XXX XXXXXX XXXXXXXXX XXXXXXXXXX 
                    XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                    XXXXXX
                        XX XXXXXXXXXX XXXXXXXX XXXXXXXXXXX
                    XXXXXXX
                XXXXXXXXX
            XXXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX
                XXXXXXXXXXXXXXX XXXXXXXX XXXXXXX XXXXXXXX
                XXXXXXXXXXXXXXX
                XXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXX XXXXXXXXXXXXXXXXXXXX XXX XXXXXX XXXXXXXXX XXXXXXXXXX
                    XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                    XXXXXX
                        XX XXXXXXXXXX XXXXXXX XXXXXXXXXXX
                    XXXXXXX
                XXXXXXXXX
            XXXXXX
            BB BBBBBBBBBBBBBBBBBBBBBB
                XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXX
            BBBBB
        XXXXXX
    XXXXXX
XXXXXXX
XX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XX XXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX