BBBBBBB BBBBBBBBBBB
BBBB BBBBBB

BBBBB BBBBBBBBBBB
 XXXXXXX   XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXX
        XXXXXX
    XXXXXX
BBBBBBBB

BBBBB BBBBBBB
XXXXXXXX XXXXXXXXXXXXXX XXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXX
            XXXXXXX XXX XXXXXXXXX
            XXXX XXXXXXX XXXXXXXXXX XXXXXXXXXXXXX
            XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXX XXXXXXXX
        XXXXXX
    XXXXXXXXXX
XXXX   XXXX XXXXXXXXXXXXXXXX XXXXXXX
        XXXX XXXXXXXXXX XXXXXXX
            XXXX XXXXXXXXXXXX XXXXXXXX XXXXXXXXX
                XXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX
                    XXXXXXX XXXXXXXXXX XXXXXXXX
                XXXXX
                XXXX XXXXXXXXXXXXX
                    XXXX
                        XX XXXXXXBBB BBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXX XXX XXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXX
                    XXXXX
                XXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXX XXXXXXX
        XXXX XXXXXXXXXX XXXXXXX
            XXXX XXXXXXXXXXXXXXX
                XXXXXXX XXX XXXXXXXXX
                XXXXXX XXX XXXX XX X XXXXX XXXXX XXXXXXXXXXX XXXXXXXXXXX
                XXX XXXXXXXXXXXXX XXXXX XXX XXXX XXXXXXXXX XX XXXXXXX XX XXXXXXXXX XXX XXXXXXXXXXX XX XXXX XXX XXXXXXXXX XXXXXXX XXXXXX XXX XXXXX XXXXXXXXX XXX XXXXXXXX XXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXX XXX XXXXX XXXXXXX XXXXXXX XXXXXX XXX XXXXXXXXX XXXXXXXXX XXX XXXXXXXX XXXXXX XXX XXXX XXXXXXXXXX
            XXXXXX
        XXXXXX
    XXXXXX    XXX     
BBBBBBBB