BB BBBBBBBBBBBBBBBBB
    XXXXXXXX
    XX XXXXXXXX
        XXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXX
    XXXX
    BB BBB BBBBBBBBBBBBBBB
        XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX
        XXXXXX
    BBBBBXXXX
    
BBBBB
XXXXX XXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXXX
    XXXXXX XXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXXBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX
XXXXXXX
XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
