BBBBBBB BBBBBBBBBBB
BBBB BBBBBB

BBBBB BBBBBBBBBBB
    XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXX
        XXXXXX
    XXXXXX
BBBBBBBB

BBBBB BBBBBBB
    XXXX XXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXX
            XXXX XXXXXXXXXX XXXXXXXXXXX XXXXXX
                XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                BBB B BB BBBBBBBBBBBBBBBBBB
                    XX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBXXXXXXXXXXXX
                        XXXXX XXXXXXXXXX XXXX XXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX
                    XXXX
                BBBBBB
                XXX XXXXXXXXXXX XXXXXX
            XXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXX
                XXXX XXXXXXXXXX XXXX XXXXXX
                    XXXX XXXXXXXXXXXXX XXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX
                            XXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXX XXXXXXXBB BBBBBBBBBBBBBBB BB BBBBBBBBBBBXXXXBBBBXXXXXBBBBBXX
                                XXXXXXX XXXXXXXXXXXXX BB BBBBBBBBBBBBBBB BB BBBBBBBBBBBXXXXXXXXBBBBBXXXXX XXXXXXXXXXXXXX
                                XXXXXXX XXXXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBB BB BBBBBBBBBBBXXXXXXXXBBBBBXXXXXX XXXX XX XXXXXXXXXXXXXX
                                XXXXXXX XXXXXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBB BB BBBBBBBBBBBBXXXXXXXXBBBBBXXXXXX XXXXX XX XXXXXXXXXXXXX
                                XXXXXXX XXXXXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBB BB BBBBBBBBBBBBXXXXXXXXBBBBBXXXXXXX XXXX XX XXXXXXXXXXXXXX
                                XXXXXXX XXXXXXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBB BB BBBBBBBBBBBBBXXXXXXXXBBBBBXXXXXXX XXXXX XX XXXXXXXXXXXXX
                                XXXXXXX XXXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBB BB BBBBBBBBBBXXXXXXXXBBBBBXXXXX XXXXXXXXXXXXXX
                                XXXXXXX XXXXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBB BB BBBBBBBBBBBXXXXXXXXBBBBBXXXXX XXXXXXXXXXXXXX
                                XXXXXXX XXXXXXXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBXXXXXXXXBBBBBXXXXXXXXX XXXXXXXXXXXXXX
                                XXXXXXX XXXXXXXXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBXXXXXXXXBBBBBXXXXXXXXX XXXXXXXXXXXXXX
                            XXXXXXXXX
                        XXXXXX
                    XXXXXX
                    XXXX XXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXX
                        XX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXXXXXXXXX
                            BB BBBBBBBBBBB BB BBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBB BB BBBBBBBBBBB
                                XXXXX XXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBXXXXXXXXXXXX XXXXXXXX X XXXXXXX
                            BBBBB
                            FFFFFF XXXXXXXXXXBB BBBBBBBBBBB XXXXX XXX XXXXXXXXXXXXXXXXXXXBBBBB
                        XXXX
                    XXXXXX
                XXXXXX
                
                XXXX XXXX XX XXX XXXXX XX XXX XXXX XXXXX XXXXXXX XXX
                XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                    
                    BBB BBBBBBBBB BB BBBBBBBBBB
                    XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXX
                        XXXX XX XXXXXX XX XXXXXX XX X XXXXX XX XXXXXX XXXXXX X XXXXXXX X X XXXXX XXXX XXXX XX XXX XXX XXXXXX
                        XX XXXXXX XX XXXXXX XX X XXXXX XXXXXX XX XXXX XXXX X XXXXXXX X X XXXXX XX XXX XXX XXXXXX XXX
                        XXXX XXXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXXX
                                XXXXXXXXXXXX
                                XXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX
                            XXXXXX
                        XXXXXX
                        XXXXXXXXXXXXX
                    XXXXXX                         
                    BBBBBB
                    XXXX XXXX XX XXX XXX XX XXX XXXX XXXXX XXXXXXX XXX
                XXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXX XXXXXXXXXXXXXX
        XX XXXXXXXXXXXXXXX XXXXXX XXXXXXX
            XX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXX
        XXXX	
    XXXXXX
BBBBBBBB

BBBBB BBBBBBBBBB
    
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
		XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
			XXXXXXXXXXXXXXXXXXXX
		XX
	XXXXXXXXX
    
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
            XXX XXXXXXXX X XXXXXXXX
            XXX XXXXXXXXXX X XXX XXXXXXXXXXXXXXXXXXXXX

            XXX XXXXXXXXXXX X XXXXXXXXXXXXXXX
            XXXXXXXXXXXXXX XX XXXXXXXXX
                XXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXX
                XXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXX

                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX

                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            X XXXX X
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            X
        XX
    XXXXXXXXX
BBBBBBBB