# Generated by Django 3.1.1 on 2020-10-16 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='plan_part_number',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='price',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='rating',
        ),
    ]
