# Generated by Django 3.1.1 on 2020-10-17 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_auto_20201016_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='category',
        ),
        migrations.DeleteModel(
            name='PlanCategory',
        ),
    ]
