# Generated by Django 3.1.1 on 2020-10-29 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
        ('planworkouts', '0003_planworkout_workout_id'),
        ('plans', '0003_auto_20201017_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='workouts',
            field=models.ManyToManyField(through='planworkouts.PlanWorkout', to='workouts.Workout'),
        ),
    ]
