# Generated by Django 3.1.1 on 2020-10-29 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planworkouts', '0003_planworkout_workout_id'),
        ('workouts', '0002_workout_plans'),
        ('plans', '0004_plan_workouts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='workouts',
            field=models.ManyToManyField(related_name='workouts', through='planworkouts.PlanWorkout', to='workouts.Workout'),
        ),
    ]
