BBBBBBB BBBBBBBBBBB
BBBB BBBBBB
BBBB BBBBBBBBBB

BBBBB BBBBBBBBB
    XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBXX
BBBBBBBB

BBBBB BBBBBBBBBBB
    XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXX
        XXXXXX
    XXXXXX
BBBBBBBB

BBBBB BBBBBBB
    XXXX XXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXX
            XXXX XXXXXXXXXXXX
                XXXX
                XXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                XXXX
            XXXXXX
        XXXXXX

        XXXX XXXXXXXXXXXX
            XXXX XXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX XXXXXX
                XX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXX
                XXXX XXXXXXXXXXXX
                    XXXX XXXXXXXXXXXX XXXXXXXXXX
                        XX XXXXXXXXXXX XXXX XXXXX XXXXXXXXXXXXXXXXXXXX
                    XXXXXX
                    XXXX XXXXXXXXXXXX XXXXXXXXXXXX
                        XX XXXXXXXXXXX XXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXX
                XXXXXX
                BBB BBBB BB BBBBBBBBBB
                    XXXX XXXXXXXXXXXX
                        XXXX XXXXXXXXXXXX XXXXXX
                            XX XXXXXXBBB BBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBXX
                                BB BBBBBBBBBBBBBBBBBB
                                    XXXX XXXXXXXXXXXXX XXXXXX XXXXXXX
                                BBBB
                                    XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX
                                BBBBB
                            XXXX
                        XXXXXX
                        XXXX XXXXXXXXXXXXXX
                            XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XX XXXXXXXXXXX XXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBFFFFFBBBBXXXBBBBBXXXX
                            XX XXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXX XXXX
                        XXXXXX
                        XXXX XXXXXXXXXXXX XXXXXXXXXXXX
                            XX XXXXXXXXXXX XXXXX XXXXXXXXXXXXX FFFFFFFFFFFFFFFFFFFFFFFFFFFXXXX
                        XXXXXX
                    XXXXXX
                BBBBBB
                XXX XXXXXXXXXXXXX
                XXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX
                    XXXX XXXXXXXXXXXX XXXXXXXXXX
                        XX XXXXXXXXXXXXXXXXXX XXXXXXXXXX
                        XX XXXXXXXXXXXXXXXXXXXXXXXXXX
                        XX XXXXXXXXXXXXXXXXXX XXXXXXXXXX
                    XXXXXX
                    XXXX XXXXXXXXXXXXXX
                        XX XXXXXXXXXXXXXX FFFFFFFFFFFFFXXXX
                        XX XXXXXXXXXXXXXX FFFFFFFFFFFFFXXXX
                        XX XXXXXXXXXXXXXXXXXXXXXX FFFFFFFFFFFFFXXXXXXXXXXXXX
                    XXXXXX
                XXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXX XXXXXXXXXX
                XX XXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXX XXX XXXX XXXXX XX XXXXXXXX XXXX XXXXXXXXX
                XXXXX XXXXXXXXBBB BBBBBBBBBBX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                    BBBBBBBBBB
                    XXXXXXXXX XXXXXXXXXXXXXX XXXX XXXXXX
                        XXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXXXX
                         FFFFFFFFFFFFFFF
                         FFFFFFFFFFFFFFF
                    XXXXXXXXXXX
                    XXXXXXXXX XXXXXXXXXXXXXX XXXX XXXXXX
                        XXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                         FFFFFFFFFFFFFFF
                         FFFFFFFFFFFFFFF
                         FFFFFFFFFFFFFFF
                         FFFFFFFFFFFFFFF
                         FFFFFFFFFFFFFFF
                         FFFFFFFFFFFFFFF
                         FFFFFFFFFFFFFFF
                        XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXX
							BB BBBBBBBBBBBBBBBBBBBBB
								XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXX XXXXXXXXXXX XX XX XXXXXXXXXXXXXXX
                                XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXX
							BBBB
								XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                                    XX XXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBXXXXXXXX XX XXXXXXXXXXX XX 
                                    XX XXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBXXXXXXXXXXX XX XXXX XXXX XXXXXXXXXXX
                                XXXXXXXX
							BBBBB
						XXXXXX
                    XXXXXXXXXXX
                    XXXXXXXXX XXXXXXXXXXXXX
                        XXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXXXX
                        XXXX X XXXXXX XXXX XXXXXXX XXXX XX XXXX XXX
                        XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                        XXXX XXXX XX XXXXXXX XXXX XXXXXX XXX
                        XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                        XXXX XXXX XXX XXXXXX XXXXXX XX XXX XXXX XX XX XXX XXX XXX XXXXXXX XXXXXX XX XXX
                        XXXXXX XXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXX

                    XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXX XXXXXX                    
						XX XXXXXXBBB BBBBBBBBBBBX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX
							XXXXX XXXXXXXXXXXXX
								XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
							XXXXXXX
							XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
						XXXX
						XXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXX
							XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
							XXXXX XXXXXXXXXXXXX
								XX XXXXXXXXXX XXXXXXXXXXXXX
							XXXXXXX
						XXXXXXXXX
						XX XXXXXXXXXXXX XXXXXXXXXXX XXXXXX
							XXXXX XXXXXXXXXXXXX
								XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
							XXXXXXX
							XXXXXXXXXX XXXX XXXX XX XXXXXXX XXXXXXXXXFFFFFFFFFFFFFXXXXXXXXXXXXXXXX
						XXXX
					XXXXXX
                XXXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXX
                XX XXXXXXXXXX XXXXX XXXXXXXXXXX XXXXXXXXXXXXX
            XXXXXXX
        XXXXX
    XXXXXX
BBBBBBBB
XXXX XXXXX XX XXXXX XXXXXX XXXXXX XXXXXXXX XXXXXXXXX XX XXXXXXXX XXXXXXXXXX XXXXXX
XX XXXX XX XXX X XXXXXXXX XXXXXXXX XXXXXX XXXXXX XXXXXXXXXXX
XX XXXXXX XXXX XXXXX XXX XXXX XX XXX XXXXXX XXXX XX XXX XXXXXXXX XXXXX XXX
BBBBB BBBBBBBBBB
    
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
BBBBBBBB