BBBBBBB BBBBBBBBBBB
BBBB BBBBBB

BBBBB BBBBBBBBBBB
    XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXX
        XXXXXX
    XXXXXX
BBBBBBBB

BBBBB BBBBBBB
    XXXX XXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXX
            XXXX XXXXXXXXXX XXXXXXXXXXX XXXXXX
                XXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                BBB B BB BBBBBBBBBBBBBBBBBB
                    XX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBXXXXXXXXXXXX
                        XXXXX XXXXXXXXXX XXXX XXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX
                    XXXX
                BBBBBB
                XXX XXXXXXXXXXX XXXXXX
            XXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXX
                XXXX XXXXXXXXXX XXXX XXXXXX
                    XXXX XXXXXXXXXXXXX XXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX
                            XXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXX XXXXXXXBB BBBBBBBBBBBBBBB BB BBBBBBBBBBBXXXXBBBBXXXXXBBBBBXX
                                XXXXXXX XXXXXXXXXXXXX BB BBBBBBBBBBBBBBB BB BBBBBBBBBBBXXXXXXXXBBBBBXXXXX XXXXXXXXXXXXXX
                                XXXXXXX XXXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBB BB BBBBBBBBBBXXXXXXXXBBBBBXXXXX XXXXXXXXXXXXXX
                                XXXXXXX XXXXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBB BB BBBBBBBBBBBXXXXXXXXBBBBBXXXXX XXXXXXXXXXXXXX
                            XXXXXXXXX
                        XXXXXX
                    XXXXXX
                    XXXX XXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXX
                        XX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXXXXXXXXX
                            BB BBBBBBBBBBB BB BBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBB BB BBBBBBBBBBB
                                XXXXX XXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBXXXXXXXXXXXXXX XXXXXXXX X XXXXXXX
                            BBBBB
                            FFFFFF XXXXXXXXXXXXBB BBBBBBBBBBB XXXXX XXX XXXXXXXXXXXXXXXXXXXBBBBB
                        XXXX
                    XXXXXX
                XXXXXX
                XXX XXXXXXXXXXXXXX
                    BBB BBBBBBBBBBB BB BBBBBBBBBBBB
                        XXX XXXXXXXXXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXXXX
                                BB BBBBBBBBBBBBBBBBBB
                                XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBXX
                                    XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXX
                                XXXX
                                BBBB
                                XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBXX
                                    XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX
                                XXXX
                                BBBBB
                            XXXXXX
                            XXXX XXXXXXXXXXXXXXXXXXXXX
                                XXX XXXXXXXXXXXXXXXXXXXXXXXX
                                XX XXXXXXXXXXXXXXXXXXXXXX 
                                XX XXXXXXXXXXXXXXXXXX
                                XXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX
                            XXXXXX
                            XXXXXX
                        XXXXX
                    BBBBBB

               XXXXX  
               

               XXXX XXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXX XXXXXXXXXXXXXX
                XX XXXXXXXXXXXXXXX XXXXXX XXXXXXX
                    XX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXX
                XXXX	
                XXXXXX
                          
               
            XXXXXX
        XXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXX XXXXXXXXXXXXXX
        XX XXXXXXXXXXXXXXX XXXXXX XXXXXXX
            XX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXX
        XXXX	
    XXXXXX
BBBBBBBB

BBBBB BBBBBBBBBB
    
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
		XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
			XXXXXXXXXXXXXXXXXXXX
		XX
	XXXXXXXXX
    
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
            XXX XXXXXXXX X XXXXXXXX
            XXX XXXXXXXXXX X XXX XXXXXXXXXXXXXXXXXXXXX

            XXX XXXXXXXXXXX X XXXXXXXXXXXXXXX
            XXXXXXXXXXXXXX XX XXXXXXXXX
                XXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXX
                XXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXX

                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX

                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            X XXXX X
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            X
        XX
    XXXXXXXXX
BBBBBBBB