# Generated by Django 3.1.1 on 2020-11-14 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_remove_orderlineitem_product_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='product_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
