XXX XXXXXXXXXXXXXXXXXXXXXXXXX
    XX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXX
            XXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX
            XX XXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX
    XXXX
    XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXX XXX XXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXX XXXXXXX
                XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXX XXX XXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXX XXXXXXXXX XXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX
                        XXXXX XXXXXXXXXXXXX
                            XX XXXXXXXXXX XXXXXXXXXXXXXXX
                        XXXXXXX
                    XXXXXXXXX
                XXXXXX
            XXXXXX
        XXXXXXX
    XXXXXX
XXXXX
XXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
    XX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXX
            XXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXX
            XX XXXXXXXXXXXXXXX XXXXXXXXXXX
        XXXXXX
    XXXX
    XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB
            BB BBBBBBBBBBBBBBBBBBBBBBBBB
                XX XXXXXXBBB BBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
            BBBBB
            
            XX XXXXXXBBB BBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        BBBB
            XX XXXXXXBBB BBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXBBB BBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        BBBBB
    XXXXXX
XXXXX
XXX XXXXXXXXXXXXXXXXXXXXXXXXX
    XX XXXXXXXBB BBBBBBBBBBBXXXXXXXXXXXX XXXXXXXXXXXXXXXXBBBBXXXXXXXXXXBBBBB XXXXXXXX XXXXXXX XXXXXXXXXX XXXXXXBBB BBBBBBBBBBBXX
        XXXX XXXXXXXXXXXXXXXXXXXX
            XXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
            XX XXXXXXXXXXXXX
                BB BBBBBBBBBBB
                    XFFFFFFFFFFFFF
                BBBB
                    XXXXX
                BBBBB
            XXXX
        XXXXXX
    XXXX
XXXXX