BBBBBBB BBBBBBBBBBBBBBBBBBB

BBBB BBBB

BBBBB BBBBBBBBBB gettext(u'Change Password') BBBBBBBB

BBBBB BBBBBBB
    XXXX gettext(u'Change Password') XXXXX

    XXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXX
        BBBBBBBBBB
        
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'Change Password') XXXXXXXXX
    XXXXXXX
BBBBBBBB
