BBBBBBB BBBBBBBBBBBBBBBBBBB

BBBB BBBB

BBBBB BBBBBBBBBB gettext(u'Signup') BBBBBBBB

BBBBB BBBBBBB
XXXX gettext(u'Sign Up') XXXXX

XXX gettext(u'Already have an account? Then please <a href="%(login_url)s">sign in</a>.') SSSSSSS SSSS SS SSSSSSSS SSSS SSSSSS SS SSSSSSSSSSSSSSSSSSSSSSSSS SSSSSSSXXXX

XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBBXX
  BBBBBBBBBB
  
  BB BBBBBBBBBBBBBBBBBBBB
  XXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXX XX
  BBBBB
  XXXXXXX XXXXXXXXXXXXXX gettext(u'Sign Up')  XXXXXXXXXXXXXXXX
XXXXXXX

BBBBBBBB
