# Generated by Django 3.1.1 on 2020-10-17 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workout_name', models.CharField(max_length=254, null=True)),
                ('description', models.TextField(null=True)),
                ('instructions', models.TextField(max_length=254, null=True)),
                ('image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('points', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
            ],
        ),
    ]
