# Generated by Django 3.1.1 on 2020-10-29 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0004_plan_workouts'),
        ('planworkouts', '0003_planworkout_workout_id'),
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='plans',
            field=models.ManyToManyField(through='planworkouts.PlanWorkout', to='plans.Plan'),
        ),
    ]
