BBBBBBB BBBBBBBBBBB
BBBB BBBBBB

BBBBB BBBBBBBBBBB
    XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXX
        XXXXXX
    XXXXXX
BBBBBBBB

BBBBB BBBBBBB
    XXXX XXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXX
            XXXX XXXXXXXXXXXXX XXXXXXXXXX
                XXXX
                XXX XXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXX
                XXXX
            XXXXXX
        XXXXXX

        XXXX XXXXXXXXXXXX
            XXXX XXXXXXXXXXXXX XXXXXXXXXX
                XXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBB BBBBBBBX XXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    BBBBBBBBBB
                    BBB BBBBB BB BBBB
                        BB BBBBBBBBBB BB BBBBBBB
                             FFFFFFFFFFFFFFF
                        BBBB
                            
                        BBBBB
                    BBBBBB
                    XXXX XXXXXXXXXXXXXXXXXXX
                        XX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXBBB BBBBBBBXXXXXXXXXXXX
                        XXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                    XXXXXX
                XXXXXXX
            XXXXXX            
        XXXXXX
    XXXXXX
BBBBBBBB

BBBBB BBBBBBBBBB
    
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
            XXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXX XXXX XX XXX XXX XXXXXXXXXXXXXXX
        XXX
    XXXXXXXXX
BBBBBBBB