XXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXX XXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX
        XXXX XXXXXXXXXXXX
            XXXX XXXXXXXXXXXX
                
                XXX XXXXXXXXXXX XXXXXX
            XXXXXX
        XXXXXX
        BB BBBBBBBBBBB BBB BBB BBBBBBBBBBBBBBB
            XX XXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXX XXXXXXXXXX XXX XXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                BBB BBBB BB BBBBBBBBBB
                    XXXX XXXXXXXXXXXX
                        XXXX XXXXXXXXXXXX XXXXXX
                            BB BBBBBBBBBBBBBBBBBB
                            XXXX XXXXXXXXXXXXX XXXXXX XXXXXXX
                            BBBB
                            XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX
                            BBBBB
                        XXXXXX
                        XXXX XXXXXXXXXXXXXX
                            XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XX XXXXXXXXXXX XXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBFFFFFBBBBXXXBBBBBXXXX
                            XX XXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXX XXXX
                        XXXXXX
                    XXXXXX
                BBBBBB
            XXXXXX
            XXXX XXXXXXXXXXXX
                XXXX XXXXXXXXXXXX
                    XXXXXXXXXX XXXXXXXXXXX XXXX XXXXXXXXXXXX
                        XXXXXBB BBBBBBBBBBBBBBBBBBB B B XXXXX XXXXXXXXXBBBBBX 
                        XXXXX XXXXXXXXXXXXXXXXXXXXXFFFFFFFFFFFFFXXXXXXX
                    XXXXXXXXXXXXX
                    BB BBBBBBBBBBBBBBBBBBB B B
                        XX XXXXXXXXXXX XXX XXXXXXXXXX XXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX
                            XXXXX XXXXXXXXXXXXXXXXXX XXXX XX XXX XXXX XXXX XXX XXXXXXXXX
                        XXXX
                    BBBBB
                    XX XXXXXXBBB BBBBBBBBBBBX XXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXXXX
                        XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXX XXXXXXXXXXXXXXX
                        XXXXX XXXXXXXXXXXXX
                            XX XXXXXXXXXX XXXXXXXXXXXXX
                        XXXXXXX
                    XXXX
                XXXXXX
            XXXXXX
        BBBBB
    XXXXXX
XXXXXX